FROM mcr.microsoft.com/devcontainers/universal:2-linux

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment if you want to install more global node packages
# RUN su vscode -c "npm install -g <your-package-list-here>"
